apiVersion: v1
kind: Pod
metadata:
  name: otel-demo
  labels:
    app: otel-demo
spec:
  containers:
    - name: otel-demo
      image: jaegertracing/example-hotrod:1.41
      ports:
        - containerPort: 8080
