apiVersion: v1
kind: Pod
metadata:
  name: rolldice
  namespace: platform
  labels:
    app: rolldice
spec:
  containers:
    - name: rolldice
      image: ghcr.io/jaegertracing/rolldice:latest
      env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://k8s-infra-otel-agent:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=rolldice"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
