apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-demo
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-demo
  template:
    metadata:
      labels:
        app: otel-demo
    spec:
      containers:
        - name: otel-demo
          image: jaegertracing/example-hotrod:latest
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://k8s-infra-otel-agent.platform.svc.cluster.local:4318"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=otel-demo,service.namespace=demo"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
