apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolldice
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rolldice
  template:
    metadata:
      labels:
        app: rolldice
    spec:
      containers:
        - name: rolldice
          image: rolldice:fixed
          ports:
            - containerPort: 5000
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://k8s-infra-otel-agent.platform.svc.cluster.local:4318"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=rolldice,service.namespace=demo"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
